<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$active_group = 'default';
$query_builder = TRUE;

$db['default'] = array(
	'dsn'	=> '',
        'hostname' => 'teendoistudio.com',
        'username' => 'teendoi1_clinicapp',
        'password' => '123456',
        'database' => 'teendoi1_clinicapp',
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

$db['logs'] = array(
    'dsn' => '',
    'hostname' => 'teendoistudio.com',
        'username' => 'teendoi1_cliniclog',
        'password' => '123456',
        'database' => 'teendoi1_cliniclog',
    // 'hostname' => 'clinicapplog.chr1i2gvjaj3.ap-southeast-1.rds.amazonaws.com',
    // 'username' => 'clinicapplog',
    // 'password' => '12345678',
    // 'database' => 'clinicapplog',
    'dbdriver' => 'mysqli',
    'dbprefix' => '',
    // 'port' => 3306,
    // 'dbprefix' => '',
    // 'pconnect' => TRUE,
    // 'db_debug' => true,
    // 'cache_on' => FALSE,
    // 'cachedir' => '',
    // 'char_set' => 'utf8',
    // 'dbcollat' => 'utf8_general_ci',
    // 'swap_pre' => '',
    // 'autoinit' => TRUE,
    // 'stricton' => FALSE,
    // 'ssl_set' => true,
    // 'ssl_key' => NULL,
    // 'ssl_cert' => NULL,
    // 'ssl_ca' => realpath('./application/third_party/mysql-ssl-ca-cert.pem'),
    // 'ssl_capath' => NULL,
    // 'ssl_cipher' => NULL,
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);
